Ver 0/SachOnline/SachOnline/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using Model.EF;
using PagedList;
using Model.ClientDAO;

namespace SachOnline.Controllers
{
    public class SachController : Controller
    {
        SachDAO sachDAO = new SachDAO();
       
        // GET: Sach
        public ActionResult Index()
        {
            return View();
        }
        
        public ViewResult ChiTietSach(int masach = 0)
        {
            Sach sach = sachDAO.ChiTietSach(masach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var chude = sach.MaChuDe;
            if (sach.SoLuong == 0)
            {
                ViewBag.Soluong = "Hết Hàng";
            }
            else {
                ViewBag.Soluong2 = "Còn Hàng";
            }
            return View(sach);

        }
        public ViewResult SachTheoTheloai(int matheloai, int? page)
        {
            ChuDe cd = sachDAO.ChiTietChuDe(matheloai);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.cd = cd.TenChuDe;
            List<Sach> SachChuDe = sachDAO.SachTheoChuDe(matheloai);
            if (SachChuDe.Count == 0)
            {
                ViewBag.ThongBao = "Không có sách nào thuộc thể loại này!";
            }
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return View(SachChuDe.ToPagedList(pageNumber, pageSize));
            //return View(SachChuDe);
        }
        public ViewResult SachTheoNXB(int maNXB, int? page)
        {
            NhaXuatBan nxb = sachDAO.ChiTietNXB(maNXB);
            if (nxb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.nxb = nxb.TenNXB;
            List<Sach> SachNXB = sachDAO.SachTheoNXB(maNXB);
            if (SachNXB.Count == 0)
            {
                ViewBag.ThongBao = "Không có sách nào thuộc nhà xuát bản này!";
            }
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return View(SachNXB.ToPagedList(pageNumber, pageSize));
        }
        //public JsonResult ListName(string q) {
        //    var data = db.Saches.Where(n=>n.TenSach.Contains(q)).Select(x=>x.TenSach).ToList();
        //    return Json(new {
        //        data = data,
        //        status = true
        //    },JsonRequestBehavior.AllowGet);
        //}
       
    }
}

Ver 0/SachOnline/SachOnline/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using System.Data.Entity;
using Model.EF;

namespace SachOnline.Controllers
{
    public class UserController : Controller
    {
        SachOnlineDbContext db = new SachOnlineDbContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang kh)
        {

            if (ModelState.IsValid)
            {
                if (db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == kh.TaiKhoan) != null)
                {
                    ModelState.AddModelError("", "Tài khoản đã có người sử dụng");
                }
                else if (db.KhachHangs.SingleOrDefault(n => n.Email == kh.Email) != null)
                {
                    ModelState.AddModelError("", "Email đã có người sử dụng");
                }
                else
                {
                    if (kh.MatKhau != null)
                    {
                        kh.MatKhau = Encryptor.MD5Hash(kh.MatKhau);
                    }
                    kh.NgayTao = DateTime.Now;
                    db.KhachHangs.Add(kh);
                    db.SaveChanges();
                    Session["TaiKhoan"] = kh;
                    Session["id"] = kh.MaKH;
                    Session["hoten"] = kh.HoTen;
                    return Redirect(Url.Action("Index", "Home"));
                }
            }


            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            System.Threading.Thread.Sleep(1000);
            string sTaiKhoan = f.Get("username").ToString();
            string sMatKhau = Encryptor.MD5Hash(f.Get("password").ToString());
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng!";
                Session["TaiKhoan"] = kh;
                Session["id"] = kh.MaKH;
                Session["hoten"] = kh.HoTen;

                return PartialView("ThongBao", "Dang Nhap thanh cong");
            }
            ModelState.AddModelError("", "Tên tài khoản hoặc mật khẩu không đúng!");
           
            return PartialView("ThongBao","Dang Nhap khong thanh cong");
        }
        [HttpGet]
        public ActionResult Edit(int maKH)
        {
            if (Session["id"] != null)
            {
                int m = int.Parse(Session["id"].ToString());
                if (m == maKH)
                {
                    KhachHang kh = new KhachHang();
                    kh = db.KhachHangs.Find(maKH);
                    return View(kh);
                }
                return Redirect(Url.Action("Index", "Home"));
            }
            else
            {
                Response.StatusCode = 404;
                return Redirect(Url.Action("Index", "Home"));
            }




        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(KhachHang kh)
        {
            var user = db.KhachHangs.SingleOrDefault(n => n.MaKH == kh.MaKH);
            user.HoTen = kh.HoTen;
            user.DiaChi = kh.DiaChi;
            user.Email = kh.Email;
            user.DienThoai = kh.DienThoai;
            user.NgaySua = DateTime.Now;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect(Url.Action("Index", "Home"));

        }
        public ActionResult Logout()
        {


            if (Session["id"] != null)
            {
                Session.Remove("id");
                Session.Remove("TaiKhoan");
                Session.Remove("hoten");
            }

            return Redirect(Url.Action("Index", "Home"));
        }
        public ActionResult QuanlyDonHang() {
            if (Session["TaiKhoan"]!=null)
            {
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                if (db.DonHangs.Where(n => n.MaKH == kh.MaKH)==null)
                {
                    return Redirect(Url.Action("Index", "Home"));
                }
                List<DonHang> lisDonHang = db.DonHangs.Where(n => n.MaKH == kh.MaKH).ToList();
                return View(lisDonHang);
            }
            return Redirect(Url.Action("Index", "Home"));
        } 
        public ActionResult XemChiTietDonHang(int maDonHang)
        {
            if (Session["TaiKhoan"] != null)
            {
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                if (db.DonHangs.Where(n => n.MaDonHang == maDonHang).SingleOrDefault(m => m.MaKH == kh.MaKH)!=null)
                {
                    List<ChiTietDonHang> listChiTiet = db.ChiTietDonHangs.Where(n => n.MaDonHang == maDonHang).ToList();
                    ViewBag.maDonHang = maDonHang;
                    return View(listChiTiet);
                }
                return Redirect(Url.Action("Index", "Home"));
            }
            return Redirect(Url.Action("Index", "Home"));

        }
    }
}

Ver 0/SachOnline/SachOnline/Views/User/DangKy.cshtml
@model KhachHang
@using Model.EF;
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Layout/UserLayout.cshtml";
}
<!-- FILTER -->
<div class="col-md-9">

    <!-- PAGE HEADER -->
    <div class="page_header1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>Tạo tài khoản</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <!-- REGISTER INFO -->
    <div class="reginfo">
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="reg-field-ico">
                <i class="fa fa-user-o"></i>
                <input class="form-control text-box single-line" type="text" name="TaiKhoan" id="TaiKhoan" placeholder="Tên tài khoản">
                <span id="taikhoan_error"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-lock"></i>
                <input class="form-control text-box single-line" type="password" name="MatKhau" id="MatKhau" placeholder="Mật khẩu">
                <span id="matkhau_error"></span>
            </div>
            <div class="reg-field-ico">
                <i class="fa fa-lock"></i>
                <input class="form-control text-box single-line" type="password" name="Re_MatKhau" id="Re_MatKhau" placeholder="Nhập lại Mật khẩu">
                <span id="re_matkhau_error"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-address-card"></i>
                <input class="form-control text-box single-line" type="text" name="HoTen" id="HoTen" placeholder="Họ và tên">
                <span id="hoten_error"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-envelope"></i>
                <input class="form-control text-box single-line" type="email" name="Email" id="Email" placeholder="Email">
                <span id="email_error"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-map-marker"></i>
                <input class="form-control text-box single-line" type="text" name="DiaChi" id="DiaChi" placeholder="Địa chỉ">
                <span id="diachi_error"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-mobile"></i>
                <input class="form-control text-box single-line" type="tel" name="DienThoai" id="DienThoai" placeholder="Số điện thoại">
                <span id="phone_err"></span>
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-calendar"></i>
                <input class="form-control text-box single-line" type="text" name="NgaySinh" id="NgaySinh" onfocus="(this.type='date')" onblur="(this.type='text')" placeholder="Ngày sinh">
            </div>
            <div class="btnReg">
                <button id="btnCreate" type="submit" value="Tạo tài khoản">Tạo tài khoản</button>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $('#btnCreate').click(function () {

        // BƯỚC 1: Lấy dữ liệu từ form
        var username = $.trim($('#TaiKhoan').val());
        var password = $.trim($('#MatKhau').val());
        var re_password = $.trim($('#Re_MatKhau').val());
        var email = $.trim($('#Email').val());
        var hoten = $.trim($('#HoTen').val());
        var address = $.trim($('#DiaChi').val());
        var phone = $.trim($('#DienThoai').val());

        // BƯỚC 2: Validate dữ liệu
        // Biến cờ hiệu
        var flag = true;

        // Username
        if (username == '' || username.length < 4) {
            $('#taikhoan_error').text('Tên tài khoản phải lớn hơn 4 ký tự');
            flag = false;
        }
        else {
            $('#taikhoan_error').text('');
        }

        // Password
        if (password.length <= 5) {
            $('#matkhau_error').text('Mật khẩu phải có ít nhất 6 kí tự');
            flag = false;
        }
        else {
            $('#matkhau_error').text('');
        }

        // Re password
        if (password != re_password) {
            $('#re_matkhau_error').text('Mật khẩu nhập lại không đúng');
            flag = false;
        }
        else {
            $('#re_password_error').text('');
        }

        // Email
        if (email == "") {
            $('#email_error').text('Email không được để trống và phải đúng định dạng');
            flag = false;
        }
        else {
            $('#email_error').text('');
        }
        // Ho Ten
        if (hoten == "") {
            $('#hoten_error').text('Họ và tên không được để trống');
            flag = false;
        }
        else {
            $('#hoten_error').text('');
        }
        if (address == "") {
            $('#diachi_error').text('Địa chỉ không được để trống');
            flag = false;
        }
        else {
            $('#diachi_error').text('');
        }
        if (phone == "") {
            $('#phone_err').text('Số điện thoại không được để trống');
            flag = false;
        } else {
            $('#phone_err').text('');
        }
        return flag;
    });
</script>

Ver 0/SachOnline/SachOnline/Views/User/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Layout/UserLayout.cshtml";
}

<div class="col-md-9">
    <!-- PAGE HEADER -->
    <div class="page_header1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>Đăng nhập</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <!-- LOGIN INFO -->
    <div class="loginfo">
        @using (Ajax.BeginForm("DangNhap", "User",new AjaxOptions() {
            HttpMethod="POST",
            LoadingElementId= "loading",
            UpdateTargetId= "kq",
            OnBegin = "Success"
        }))
        {
            <span class="notify-login">@ViewBag.ThongBao</span>
            @*<form method="post">*@
            <div class="input-field-ico">
                <i class="fa fa-user-o"></i>
                <input type="text" name="username" id="username" placeholder="Tên tài khoản" required="required" />
            </div>
            <div class="input-field-ico">
                <i class="fa fa-lock"></i>
                <input type="password" name="password" id="password" placeholder="Mật khẩu" required="required" />
            </div>
            <button type="submit">Đăng nhập</button>
            <span>Bạn chưa có tài khoản?<a href="@Url.Content("~/User/Dangky")">Tạo tài khoản</a></span>
            @*</form>*@
        }
        
        <div id="myModal" class="modal " style="margin:0 auto; padding-top:200px;">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body" id="kq">
                        <div id="loading" style="display:none">
                            <img src="~/Content/User/images/giphy.gif" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  
    function Success() {
        $('#myModal').show();
        window.setTimeout(hide_modal, 4000);
    }
    function show_modal() {
        $('#myModal').show();
    }

    function hide_modal() {
        $('#myModal').hide();
    }
</script>

Ver 0/SachOnline/SachOnline/Views/User/Edit.cshtml
@model KhachHang
@using Model.EF;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/UserLayout.cshtml";
}
<!-- FILTER -->
<div class="col-md-9">

    <!-- PAGE HEADER -->
    <div class="page_header1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>Thông tin tài khoản</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <!-- REGISTER INFO -->
    <div class="reginfo">
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="reg-field-ico">
                <i class="fa fa-address-card"></i>
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                <span id="hoten_error"></span>
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-envelope"></i>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                <span id="email_error"></span>
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-map-marker"></i>
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                <span id="diachi_error"></span>
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-mobile"></i>
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                <span id="phone_err"></span>
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>

            <div class="reg-field-ico">
                <i class="fa fa-calendar"></i>
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
            <div class="btnReg">
                <button id="btnCreate" type="submit" value="Tạo tài khoản">Lưu thông tin</button>
            </div>
        }
    </div>
</div>
<script type="text/javascript">
        $('#btnCreate').click(function () {

            // BƯỚC 1: Lấy dữ liệu từ form
            var email = $.trim($('#Email').val());
            var hoten = $.trim($('#HoTen').val());
            var address = $.trim($('#DiaChi').val());
            var phone = $.trim($('#DienThoai').val());

            // BƯỚC 2: Validate dữ liệu
            // Biến cờ hiệu
            var flag = true;

            // Email
            if (email=="") {
                $('#email_error').text('Email không được để trống và phải đúng định dạng');
                flag = false;
            }
            else {
                $('#email_error').text('');
            }
                // Ho Ten
            if (hoten=="") {
                $('#hoten_error').text('Họ Tên không được để trống');
                flag = false;
            }
            else {
                $('#hoten_error').text('');
            }
            if (address == "") {
                $('#diachi_error').text('Địa Chỉ không được để trống');
                flag = false;
            }
            else {
                $('#diachi_error').text('');
            }
            if (phone == "") {
                $('#phone_err').text('Số Điện Thoại không được để trống');
                flag = false;
            } else {
                $('#phone_err').text('');
            }
            return flag;
        });
</script>

Ver 0/SachOnline/SachOnline/Views/User/QuanlyDonHang.cshtml
@using Model.EF;
@model List<DonHang>
@{
    ViewBag.Title = "QuanlyDonHang";
    Layout = "~/Views/Layout/UserLayout.cshtml";
}

<!-- FILTER -->
<div class="col-md-9">

    <!-- PAGE HEADER -->
    <div class="page_header1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>Xem đơn hàng</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <table class="order-view">
        <tr>
            <th>Mã đơn hàng</th>
            <th>Ngày đặt hàng</th>
            <th>Số tiền thanh toán</th>
            <th>Tình trạng</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.MaDonHang</td>
                <td>@item.NgayDat</td>
                <td>@string.Format("{0:0,0 VNĐ}", item.TongGia).Replace(",", ".")</td>
                <td>Đang chờ xác nhận</td>
                <td><a href="@Url.Action("XemChiTietDonHang","User",new { @maDonHang = item.MaDonHang})">Xem chi tiết</a></td>
            </tr>
        }
    </table>

</div>

Ver 0/SachOnline/SachOnline/Views/User/XemChiTietDonHang.cshtml
@using Model.EF;
@using SachOnline.Models
@model List<ChiTietDonHang>
@{
    ViewBag.Title = "XemChiTietDonHang";
    Layout = "~/Views/Layout/UserLayout.cshtml";
}

<!-- FILTER -->
<div class="col-md-9">

    <!-- PAGE HEADER -->
    <div class="page_header1">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>Chi tiết đơn hàng</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    @{
        SachOnlineDbContext db = new SachOnlineDbContext();
    }

    <h4 class="order-info-title">Thông tin người nhận</h4>
    <table class="order-info">
        @{
            DonHang dh = db.DonHangs.Find(ViewBag.maDonHang);
            GiaoHang gh = db.GiaoHangs.Find(dh.MaGiaoHang);
            <tr>
                <th>Tên người nhận</th>
                <td>@gh.TenNguoiNhan</td>
            </tr>
            <tr>
                <th>Địa chỉ</th>
                <td>@gh.DiaChi</td>
            </tr>
            <tr>
                <th>Số điện thoại</th>
                <td>@gh.SDT</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@gh.Email</td>
            </tr>
            <tr>
                <th>Lời nhắn</th>
                <td>@gh.LoiNhan</td>
            </tr>
        }
    </table>

    <div class="order-checkout">
        <ul>
            <li>Tổng giá tiền sách<span>@string.Format("{0:0,0 VNĐ}", dh.TongGia).Replace(",", ".")</span></li>
            <li>Chiết khấu<span>0%</span></li>
            <li>Phí vận chuyển<span>MIỄN PHÍ</span></li>
        </ul>
        <span class="total-text">Tổng tiền thanh toán</span><span class="total-price">@string.Format("{0:0,0 VNĐ}", dh.TongGia).Replace(",", ".")</span>
    </div>

    <div class="clearfix"></div>

    <h4 class="order-info-title">Sách đã đặt</h4>
    <table class="order-info-book">
        <tr>
            <th colspan="2">Tên sách</th>
            <th>Số lượng</th>
            <th>Giá tiền</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                @{
                    Sach sach = db.Saches.Find(item.MaSach);
                    <td colspan="2">
                        <img src="@Url.Content("~/Content/img-sp/"+sach.AnhBia)" class="img-responsive" alt="" />
                        <h4><a href="@Url.Action("ChiTietSach","Sach",new { @masach=sach.MaSach})">@sach.TenSach</a></h4>
                    </td>
                    <td>@item.SoLuong</td>
                    <td><span>@string.Format("{0:0,0 VNĐ}", item.DonGia).Replace(",", ".")</span></td>
                }
            </tr>
                    }
    </table>

</div>