Ver 0/SachOnline/SachOnline/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EF;
using Model.ClientDAO;


namespace SachOnline.Controllers.User
{
    public class PartialController : Controller
    {
        SachDAO sach = new SachDAO();
        public PartialViewResult TheLoaiPartial()
        {
            var ListTheLoai = sach.MenuChuDe();
            return PartialView(ListTheLoai);
        }
        public PartialViewResult NhaXuatBanPartial()
        {
            var ListNhaXuatBan = sach.MenuNXB();
            return PartialView(ListNhaXuatBan);
        }
    }
}

Ver 0/SachOnline/SachOnline/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using System.Data.Entity;
using Model.EF;

namespace SachOnline.Controllers
{
    public class UserController : Controller
    {
        SachOnlineDbContext db = new SachOnlineDbContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang kh)
        {

            if (ModelState.IsValid)
            {
                if (db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == kh.TaiKhoan) != null)
                {
                    ModelState.AddModelError("", "Tài khoản đã có người sử dụng");
                }
                else if (db.KhachHangs.SingleOrDefault(n => n.Email == kh.Email) != null)
                {
                    ModelState.AddModelError("", "Email đã có người sử dụng");
                }
                else
                {
                    if (kh.MatKhau != null)
                    {
                        kh.MatKhau = Encryptor.MD5Hash(kh.MatKhau);
                    }
                    kh.NgayTao = DateTime.Now;
                    db.KhachHangs.Add(kh);
                    db.SaveChanges();
                    Session["TaiKhoan"] = kh;
                    Session["id"] = kh.MaKH;
                    Session["hoten"] = kh.HoTen;
                    return Redirect(Url.Action("Index", "Home"));
                }
            }


            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            System.Threading.Thread.Sleep(1000);
            string sTaiKhoan = f.Get("username").ToString();
            string sMatKhau = Encryptor.MD5Hash(f.Get("password").ToString());
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng!";
                Session["TaiKhoan"] = kh;
                Session["id"] = kh.MaKH;
                Session["hoten"] = kh.HoTen;

                return PartialView("ThongBao", "Dang Nhap thanh cong");
            }
            ModelState.AddModelError("", "Tên tài khoản hoặc mật khẩu không đúng!");
           
            return PartialView("ThongBao","Dang Nhap khong thanh cong");
        }
        [HttpGet]
        public ActionResult Edit(int maKH)
        {
            if (Session["id"] != null)
            {
                int m = int.Parse(Session["id"].ToString());
                if (m == maKH)
                {
                    KhachHang kh = new KhachHang();
                    kh = db.KhachHangs.Find(maKH);
                    return View(kh);
                }
                return Redirect(Url.Action("Index", "Home"));
            }
            else
            {
                Response.StatusCode = 404;
                return Redirect(Url.Action("Index", "Home"));
            }




        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(KhachHang kh)
        {
            var user = db.KhachHangs.SingleOrDefault(n => n.MaKH == kh.MaKH);
            user.HoTen = kh.HoTen;
            user.DiaChi = kh.DiaChi;
            user.Email = kh.Email;
            user.DienThoai = kh.DienThoai;
            user.NgaySua = DateTime.Now;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect(Url.Action("Index", "Home"));

        }
        public ActionResult Logout()
        {


            if (Session["id"] != null)
            {
                Session.Remove("id");
                Session.Remove("TaiKhoan");
                Session.Remove("hoten");
            }

            return Redirect(Url.Action("Index", "Home"));
        }
        public ActionResult QuanlyDonHang() {
            if (Session["TaiKhoan"]!=null)
            {
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                if (db.DonHangs.Where(n => n.MaKH == kh.MaKH)==null)
                {
                    return Redirect(Url.Action("Index", "Home"));
                }
                List<DonHang> lisDonHang = db.DonHangs.Where(n => n.MaKH == kh.MaKH).ToList();
                return View(lisDonHang);
            }
            return Redirect(Url.Action("Index", "Home"));
        } 
        public ActionResult XemChiTietDonHang(int maDonHang)
        {
            if (Session["TaiKhoan"] != null)
            {
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                if (db.DonHangs.Where(n => n.MaDonHang == maDonHang).SingleOrDefault(m => m.MaKH == kh.MaKH)!=null)
                {
                    List<ChiTietDonHang> listChiTiet = db.ChiTietDonHangs.Where(n => n.MaDonHang == maDonHang).ToList();
                    ViewBag.maDonHang = maDonHang;
                    return View(listChiTiet);
                }
                return Redirect(Url.Action("Index", "Home"));
            }
            return Redirect(Url.Action("Index", "Home"));

        }
    }
}

Ver 0/SachOnline/SachOnline/Views/Layout/NoSideBarLayout.cshtml
@using Model.EF;
<!DOCTYPE html>
<html>
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <title>Sách Online</title>
    <meta name="keywords" content="bán sách online, bán sách trục tuyến">
    <meta name="description" content="Website bán sách trực tuyến">
    <meta name="author" content="Project">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico">

    <!-- CSS -->
    <link rel="stylesheet" href="~/Content/User/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/User/css/menu.css">
    <link rel="stylesheet" href="~/Content/User/css/style.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/isotope/isotope.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/slick/slick.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/flex-slider/flexslider.css" />
    <!-- jQuery -->
    <script src="~/Content/User/js/jquery.js"></script>
    <script src="~/Content/User/js/bootstrap.min.js"></script>
    <script src="~/Content/User/js/vendor/isotope/isotope.pkgd.js"></script>
    <script src="~/Content/User/js/vendor/slick/slick.js"></script>
    <script src="~/Content/User/js/vendor/owl-carousel/owl.carousel.js"></script>
    <script src="~/Content/User/js/jquery-ui.js"></script>
    <script src="~/Content/User/js/jquery.animateNumber.js"></script>
    <script src="~/Content/User/js/jquery.appear.js"></script>
    <script src="~/Content/User/js/jquery.inview.js"></script>
    <script src="~/Content/User/js/jquery.easing.min.js"></script>
    <script src="~/Content/User/js/vendor/easypiechart/jquery.easypiechart.min.js"></script>
    <script src="~/Content/User/js/vendor/flex-slider/jquery.flexslider.js"></script>
    <script src="~/Content/User/js/vendor/flex-slider/main.js"></script>
    <script src="/Content/User/js/main.js"></script>
    <!-- Icon Fonts -->
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="/js/html5shiv.js"></script>
        <script src="/js/respond.min.js"></script>
    <![endif]-->
    <!-- Addthis Script -->
    <script src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54d4ff3177e34cbf" async="async"></script>

</head>

<body class="no-padding royal_preloader" id="page-top" data-spy="scroll" data-target="#myScrollspy">

    <div class="body">

        <div class="header-wrap">

            <!-- TOPBAR -->
            <div class="topbar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 tb-left">
                            <ul>
                                <li><span class="fa fa-phone"></span>1900-123-456</li>
                                <li><span class="fa fa-envelope-o"></span>sach_online@gmail.com</li>
                            </ul>
                        </div>
                        <div class="col-md-6 tb-right">
                            <ul class="pull-right">
                                <li><span class="fa fa-map-marker"></span>285 Đội Cấn, quận Ba Đình, tp Hà Nội</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- HEADER -->
            <header>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 logo">
                            <a href="~/Home"><img src="~/Content/User/images/logo.png" class="img-responsive" alt="" /></a>
                        </div>

                        <div class="col-md-6">
                            @using (Html.BeginForm("TimKiem", "TimKiem", FormMethod.Post, new { @class = "search-menu" }))
                            {
                                <input type="text" name="txtTimKiem" placeholder="Nhập tên sách cần tìm...">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            }
                        </div>

                        <div class="col-md-9">
                            <div class="shop-cart pull-right">
                                @Html.Action("TongSachPar", "GioHang")
                            </div>

                            <div id='navmenu' class="pull-right">
                                <ul>
                                    @{  SachOnlineDbContext db = new SachOnlineDbContext();

                                        if (Session["TaiKhoan"] != null)
                                        {
                                            <li>
                                                <a class="user-text">@Session["hoten"]</a>
                                                <ul>
                                                    <li><a href='@Url.Content("~/User/Dangky")'>Xem đơn hàng</a></li>
                                                    <li><a href='@Url.Action("Edit","User",new { @maKH=Session["id"]})'>Thông tin tài khoản</a></li>
                                                    <li><a href='@Url.Action("Logout","User")'>Thoát</a></li>
                                                </ul>
                                            </li>
                                        }
                                        else
                                        {
                                            <li><a href='@Url.Content("~/User/DangNhap")'>Đăng nhập</a></li>
                                            <li><a href='@Url.Content("~/User/Dangky")'>Tạo tài khoản</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>

        <!-- SHOP CONTENT MAIN -->
        <div class="shop-main">
            <div class="container">
                <div class="row">

                    <!-- SHOP CONTENT -->
                    @RenderBody()

                </div>
            </div>
        </div>

        <!-- FOOTER -->
        <footer>
            <div class="overlay3"></div>
            <div class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 footer-widget">
                            <div class="f-logo"><img src="~/Content/User/images/logo.png" class="img-responsive space30" alt="" /></div>
                            <p>Chúng tôi là đơn vị bán sách luôn đặt uy tín lên hàng đầu. Đem lại những quyển sách tốt nhất cho quý khách hàng.</p>
                        </div>

                        <div class="col-md-3 footer-widget">
                            <h5>Từ khoá</h5>
                            <ul class="tags">
                                <li><a href="#">Yoga</a></li>
                                <li><a href="#">Fitness</a></li>
                                <li><a href="#">Body Building</a></li>
                                <li><a href="#">Gym</a></li>
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Fit</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Weight Loss</a></li>
                                <li><a href="#">Yoga</a></li>
                                <li><a href="#">Fitness</a></li>
                                <li><a href="#">Body Building</a></li>
                                <li><a href="#">Gym</a></li>
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Fit</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Weight Loss</a></li>
                            </ul>
                        </div>

                        <div class="col-md-6 footer-widget">
                            <ul class="f-social">
                                <li><a href="https://www.facebook.com/" class="fa fa-facebook"></a></li>
                                <li><a href="https://twitter.com/" class="fa fa-twitter"></a></li>
                                <li><a href="https://plus.google.com/" class="fa fa-google-plus"></a></li>
                                <li><a href="https://www.linkedin.com/" class="fa fa-linkedin"></a></li>
                                <li><a href="https://www.youtube.com/" class="fa fa-youtube"></a></li>
                                <li><a href="https://vimeo.com/" class="fa fa-vimeo-square"></a></li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <p class="copy-right">&copy; Copyright 2017 - Project được thực hiện bởi nhóm</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

Ver 0/SachOnline/SachOnline/Views/Layout/UserLayout.cshtml
@using Model.EF;
<!DOCTYPE html>
<html>
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <title>Sách Online</title>
    <meta name="keywords" content="bán sách online, bán sách trục tuyến">
    <meta name="description" content="Website bán sách trực tuyến">
    <meta name="author" content="Project">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- jQuery -->
    <script src="~/Content/User/js/jquery.js"></script>
    <script src="~/Content/User/js/bootstrap.min.js"></script>
    <script src="~/Content/User/js/vendor/isotope/isotope.pkgd.js"></script>
    <script src="~/Content/User/js/vendor/slick/slick.js"></script>
    <script src="~/Content/User/js/vendor/owl-carousel/owl.carousel.js"></script>
    <script src="~/Content/User/js/jquery-ui.js"></script>
    <script src="~/Content/User/js/jquery.animateNumber.js"></script>
    <script src="~/Content/User/js/jquery.appear.js"></script>
    <script src="~/Content/User/js/jquery.inview.js"></script>
    <script src="~/Content/User/js/jquery.easing.min.js"></script>
    <script src="~/Content/User/js/vendor/easypiechart/jquery.easypiechart.min.js"></script>
    <script src="~/Content/User/js/vendor/flex-slider/jquery.flexslider.js"></script>
    <script src="~/Content/User/js/vendor/flex-slider/main.js"></script>
    <script src="/Content/User/js/main.js"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="~/Content/User/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/User/css/menu.css">
    <link rel="stylesheet" href="~/Content/User/css/style.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/isotope/isotope.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/slick/slick.css">
    <link rel="stylesheet" href="~/Content/User/js/vendor/flex-slider/flexslider.css" />
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- Icon Fonts -->
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="/js/html5shiv.js"></script>
        <script src="/js/respond.min.js"></script>
    <![endif]-->
    <!-- Addthis Script -->
    <script src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54d4ff3177e34cbf" async="async"></script>

</head>

<body class="no-padding royal_preloader" id="page-top" data-spy="scroll" data-target="#myScrollspy">

    <div class="body">

        <div class="header-wrap">

            <!-- TOPBAR -->
            <div class="topbar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 tb-left">
                            <ul>
                                <li><span class="fa fa-phone"></span>1900-123-456</li>
                                <li><span class="fa fa-envelope-o"></span>sach_online@gmail.com</li>
                            </ul>
                        </div>
                        <div class="col-md-6 tb-right">
                            <ul class="pull-right">
                                <li><span class="fa fa-map-marker"></span>285 Đội Cấn, quận Ba Đình, tp Hà Nội</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- HEADER -->
            <header>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 logo">
                            <a href="/"><img src="~/Content/User/images/logo.png" class="img-responsive" alt="" /></a>
                        </div>

                        <div class="col-md-6">

                            @using (Html.BeginForm("TimKiem", "TimKiem", FormMethod.Post, new { @class = "search-menu" }))
                            {

                                <input type="text" name="txtTimKiem" placeholder="Nhập tên sách cần tìm...">
                                <button type="submit"><i class="fa fa-search"></i></button>

                            }
                        </div>

                        <div class="col-md-9">
                            <div class="shop-cart pull-right">
                                @Html.Action("TongSachPar", "GioHang")
                            </div>

                            <div id='navmenu' class="pull-right">
                                <ul>
                                    @{  SachOnlineDbContext db = new SachOnlineDbContext();

                                        if (Session["TaiKhoan"] != null)
                                        {
                                            <li>
                                                <a class="user-text">@Session["hoten"]</a>
                                                <ul>
                                                    <li><a href='@Url.Action("QuanLyDonHang","User")'>Xem đơn hàng</a></li>
                                                    <li><a href='@Url.Action("Edit","User",new { @maKH=Session["id"]})'>Thông tin tài khoản</a></li>
                                                    <li><a href='@Url.Action("Logout","User")'>Thoát</a></li>
                                                </ul>
                                            </li>
                                        }
                                        else
                                        {
                                            <li><a href='@Url.Content("~/dang-nhap")'>Đăng nhập</a></li>
                                            <li><a href='@Url.Content("~/dang-ky")'>Tạo tài khoản</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>

        <!-- SHOP CONTENT MAIN -->
        <div class="shop-main">
            <div class="container">
                <div class="row">

                    <!-- SIDEBAR -->
                    <div class="col-md-3 sidebar">
                        <div class="sbar-widget">
                            <h5>Danh mục</h5>
                            <div class="toggle1">
                                <div class="title">
                                    <a class="toggle-trigger1">Thể loại sách</a>
                                </div>
                                <div class="toggle-content1">
                                    <ul>
                                        @Html.Action("TheLoaiPartial", "Partial")
                                    </ul>
                                </div>
                            </div>
                            <div class="toggle1">
                                <div class="title">
                                    <a class="toggle-trigger1">Nhà xuất bản</a>
                                </div>
                                <div class="toggle-content1">
                                    <ul>
                                        @Html.Action("NhaXuatBanPartial", "Partial")
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="side-img">
                            <img src="~/Content/User/images/side-img1.jpg" alt="">
                            <img src="~/Content/User/images/side-img2.jpg" alt="">
                            <img src="~/Content/User/images/side-img3.jpg" alt="">
                        </div>
                    </div>

                    <!-- SHOP CONTENT -->
                    @RenderBody()

                </div>
            </div>
        </div>

        <!-- FOOTER -->
        <footer>
            <div class="overlay3"></div>
            <div class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 footer-widget">
                            <div class="f-logo"><img src="~/Content/User/images/logo.png" class="img-responsive space30" alt="" /></div>
                            <p>Chúng tôi là đơn vị bán sách luôn đặt uy tín lên hàng đầu. Đem lại những quyển sách tốt nhất cho quý khách hàng.</p>
                        </div>

                        <div class="col-md-3 footer-widget">
                            <h5>Từ khoá</h5>
                            <ul class="tags">
                                <li><a href="#">Yoga</a></li>
                                <li><a href="#">Fitness</a></li>
                                <li><a href="#">Body Building</a></li>
                                <li><a href="#">Gym</a></li>
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Fit</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Weight Loss</a></li>
                                <li><a href="#">Yoga</a></li>
                                <li><a href="#">Fitness</a></li>
                                <li><a href="#">Body Building</a></li>
                                <li><a href="#">Gym</a></li>
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Fit</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Weight Loss</a></li>
                            </ul>
                        </div>

                        <div class="col-md-6 footer-widget">
                            <ul class="f-social">
                                <li><a href="https://www.facebook.com/" class="fa fa-facebook"></a></li>
                                <li><a href="https://twitter.com/" class="fa fa-twitter"></a></li>
                                <li><a href="https://plus.google.com/" class="fa fa-google-plus"></a></li>
                                <li><a href="https://www.linkedin.com/" class="fa fa-linkedin"></a></li>
                                <li><a href="https://www.youtube.com/" class="fa fa-youtube"></a></li>
                                <li><a href="https://vimeo.com/" class="fa fa-vimeo-square"></a></li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <p class="copy-right">&copy; Copyright 2017 - Project được thực hiện bởi nhóm</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>